[project]
name = "optics"
version = "1.0.0"
dependencies = ["numpy>=1.25.2", "scipy>=1.11.2","uncertainties>=3.1.7",]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"